-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE 
WHERE TLNO IS NOT NULL
AND GENDER = 'W'
AND MONTH(DATE_OF_BIRTH) = 3
ORDER BY MEMBER_ID ASC;

-- refactoring

# 생일이 3월인 여성
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d')
FROM MEMBER_PROFILE
WHERE DATE_FORMAT(DATE_OF_BIRTH, '%m') = 3
AND GENDER LIKE 'W'
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;
