-- 코드를 입력하세요
# 상반기 아이스크림 주문량 >= 3000 && 주 성분이 과일인 맛 
SELECT A.FLAVOR
FROM FIRST_HALF A
JOIN ICECREAM_INFO B
ON A.FLAVOR = B.FLAVOR
WHERE TOTAL_ORDER >= 3000
AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;