-- 코드를 입력하세요
# SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%y-%m-%d') AS PUBLISHED_DATE
# FROM BOOK
# WHERE Year(PUBLISHED_DATE) = 2021
# AND CATEGORY = '인문'
# ORDER BY PUBLISHED_DATE ASC;

SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") as PUBLISHED_DATE
-- as를 해야 컬럼명이 저렇게 나옵니다. 
FROM BOOK
WHERE Year(PUBLISHED_DATE) = 2021 AND CATEGORY = "인문"
ORDER BY PUBLISHED_DATE ;