-- 코드를 입력하세요
# 상반기 각 아이스크림 성분 타입과 성분 타입에 대한 총 주문량을 총주문량 작은 순서대로 조회
SELECT I.INGREDIENT_TYPE, SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS F
JOIN ICECREAM_INFO AS I
ON F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY 2 ASC;